### ISSUE TITLE
Make all pages extend a base template with nav bar

### ISSUE THREAD

**Issue by chris-anderson67** [jumbocodefall2017/NorthShoreCDC#101]
I'm pretty sure you can just make a base template html filed, and have a place where the page content gets inserted like:` {% block page_content %}{% endblock %}`. And then in the template file for each page make it `{% extends "base.html" %}` at the top, and start and end a block of the same name: 
```
{% block page_content %}
<div>
The whole page        
</div>
{% endblock %}
```

**Comment by chris-anderson67** [comment]
https://github.com/chris-anderson67/VotePledge/tree/master/app/templates — A set of templates from a trash flask I made.

**Comment by bsteephenson** [comment]
Pr #109
