### ISSUE TITLE
Connect Firebase to Flask App

### ISSUE THREAD

**Issue by chris-anderson67** [jumbocodefall2017/NorthShoreCDC#16]
http://burhan.io/flask-web-api-with-firebase/

This tutorial should help a lot with using the Python Firebase Api

**Comment by chris-anderson67** [comment]
This will require creating a google account for the project and setting up the firebase GUI console, as well as adding the dependency to the flask app.

Lets start by trying to add things to the DB.

**Comment by Silverbaq** [comment]
If you like, I can setup the firebase part for your flask app.
