### ISSUE TITLE
Implement base ui elements from our design.

### ISSUE THREAD

**Issue by chris-anderson67** [jumbocodefall2017/NorthShoreCDC#17]
We should have designs to work with on Thursday.

**Comment by bsteephenson** [comment]
Stuff that should be useful

https://github.com/airbnb/react-native-maps
https://github.com/jaysoo/react-native-parallax-scroll-view
https://github.com/react-native-training/react-native-elements (pretty components)
https://github.com/jayesbe/react-native-cacheable-image (automatically cache images from a url)

And a bunch more here

http://www.awesome-react-native.com/#components

**Comment by chris-anderson67** [comment]
![22404179_1895723883775059_660942623_o](https://user-images.githubusercontent.com/5971478/31392183-9b620376-ada6-11e7-8ffd-94ca06618295.png)

**Comment by chris-anderson67** [comment]
We need to build
* The Gallery page including a grid of images -> clicking an image launches a new mural detail view
* The Map page rendering a map with some testing markers
* The Contact page with accordion style list
